# Generated by Django 4.1.7 on 2023-03-27 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treemenu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menunames',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
